name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of SonarCloud reporting
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test:coverage
      - name: fix code coverage paths
        working-directory: ./coverage
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' lcov.info
      # The build is already made by Vercel when deploying
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
